version: '3'

services:
  gateway-server:
    image: gateway:0.0.1
    container_name: gateway-server
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: gateway-server
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - mongo-db

  auth-server:
    image: auth:0.0.1
    container_name: auth-server
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: auth-server
    volumes:
      - ./:/app
    depends_on:
      - mongo-db

  event-server:
    image: event:0.0.1
    container_name: event-server
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: event-server
    volumes:
      - ./:/app
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_USERNAME=${MONGO_INITDB_USERNAME}
      - MONGO_INITDB_PASSWORD=${MONGO_INITDB_PASSWORD}
